### ISSUE TITLE
Connect to USB host. 

### ISSUE THREAD

**Issue by MoreTore** [commaai/agnos-builder#108]
I am trying to connect my PC to the comma 3 with the goal of high speed/low latency  isochronous usb transfer for video streaming. I am stuck at square one and I am wondering if the hardware is capable of this. With the C3 powered from the primary usb port, I cannot get the other port to be recognized by my PC. If the primary usb port is unplugged my PC will recognize a QUSB BULK device.

**Comment by adeebshihadeh** [comment]
[Discord](https://discord.comma.ai) is the right place for this.

**Comment by MoreTore** [comment]
> [Discord](https://discord.comma.ai) is the right place for this.

You should unban me 🙃
