### ISSUE TITLE
add timeout to ABL reset prompt

### ISSUE THREAD

**Issue by jyoung8607** [commaai/agnos-builder#143]
Self-recover in case of unintended entry to the ABL reset menu, exit and boot normally. Gets an unattended device back on WiFI for remote access, and prevents screen burn-in and/or battery drain.

Perhaps 30 seconds? A visual countdown timer would be nice-to-have, but mainly gold-plating.

**Comment by adeebshihadeh** [comment]
@robbederks up to you if you think this is worth the effort to implement. seems nice to have, but not at the expense of more complexity or a bunch of time.

**Comment by robbederks** [comment]
Doesn't sound too complex to implement if we don't care about displaying it. 30s sounds fine to not be confusing

**Comment by robbederks** [comment]
Implemented a 60s timeout!
