### ISSUE TITLE
ABL: fastboot doesn't work with USB3

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/agnos-builder#145]
Enters fastboot just fine but reboots as soon as any command is sent.

**Comment by robbederks** [comment]
Some USB logs from the XBL USB driver that's being used:
[bad.log](https://github.com/commaai/agnos-builder/files/11801510/bad.log)
[good.log](https://github.com/commaai/agnos-builder/files/11801511/good.log)

**Comment by robbederks** [comment]
Should be fixed in https://github.com/commaai/edk2_tici/commit/139cb829b97a43e67a1a6204f0d7aea3e8dc152e
