### ISSUE TITLE
XBL/ABL bootsplash blink

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/agnos-builder#173]
Doesn't happen often, but I've seen it enough to be confident it's real

**Comment by robbederks** [comment]
what kind of blink? when?

**Comment by adeebshihadeh** [comment]
It’s very early, seems to be around the time of XBL -> ABL. Display just goes blank for <1s then back to comma.

**Comment by robbederks** [comment]
There was a very short flicker that was always present which I fixed here: https://github.com/commaai/edk2_tici/pull/19

Not sure if this is the one you're talking about, but doesn't sound unlikely that the ones you noticed are this but just more pronounced for whatever reason
