### ISSUE TITLE
Factory reset triggers upon restarting comma service

### ISSUE THREAD

**Issue by nworb-cire** [commaai/agnos-builder#212]
It looks like [this line](https://github.com/commaai/agnos-builder/blob/2de31e2006eb0bf9616a719c81f97c21cc1d563f/userspace/usr/comma/comma.sh#L51) is a bit trigger happy and will throw up the factory reset screen too easily.

Steps to reproduce:
- clean install of openpilot
- boot device onroad
- touch various UI elements until `cat /sys/devices/platform/soc/894000.i2c/i2c-2/2-0017/touch_count` > 4
- run `sudo systemctl restart comma` over SSH
- you will see the factory reset screen present itself

**Comment by adeebshihadeh** [comment]
The service isn't really designed to be restarted. I'd merge a clean PR to fix it, but I wouldn't call this an issue.
