### ISSUE TITLE
Taps not cleared on comma service restart, triggering system reset

### ISSUE THREAD

**Issue by incognitojam** [commaai/agnos-builder#213]
This seems to happen reliably: running `systemctl restart comma` after the device has booted (and after tapping the UI, although I have not tested without doing this) causes the device to get stuck in the reset script.

I'm not sure if it's a seperate issue, but the device shows a black screen instead of actually opening the system reset app.

https://github.com/commaai/agnos-builder/blob/2de31e2006eb0bf9616a719c81f97c21cc1d563f/userspace/usr/comma/comma.sh#L51

**Comment by adeebshihadeh** [comment]
Duplicate of #212
