### ISSUE TITLE
fastboot CLI in edl

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/agnos-builder#217]
The goal is to make https://github.com/bkerler/edl as nice to use on the command line as [fastboot](https://manpages.ubuntu.com/manpages/focal/man1/fastboot.1.html).

Must have
* all commands listed below
* less verbose output; don't need to change edl's output to match fastboot, just show less of it

Minimum supported commands
```
fastboot devices
fastboot flash
fastboot reboot
fastboot --set-active=a
fastboot continue
```

Extra $100 for `fastboot format:ext4` support.

**Comment by bongbui321** [comment]
I don't think we can have something similar to `fastboot continue` since we basically loading our own secondary bootloader (programmer/loader in this case) use commands in QDL mode, while `fastboot continue` continues the booting process from `abl`.
