### ISSUE TITLE
How can others build it?

### ISSUE THREAD

**Issue by domhel** [commaai/agnos-builder#239]
Hi there,

I was looking into a bounty but I've noticed that I can't even build the image, as two repos are private.
Is there any way to get around this, or how are we supposed to do the tasks?

Thanks

**Comment by andiradulescu** [comment]
the private repos are not needed for `build_kernel.sh` and `build_system.sh`. you shouldn’t need to run/build anything else.

**Comment by domhel** [comment]
Thanks, got it.
The problem was that `git clone --recurse-submodules ...` for some reason deleted all the files in agnos-kernel-sdm845 and I had to git reset that submodule.
