### ISSUE TITLE
The following actions uses Node.js version which is deprecated and will be forced to run on node20

### ISSUE THREAD

**Issue by ParsaNobahari** [commaai/agnos-builder#255]
I just noticed that when running pre-commit action in github, there is warning message:

> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/setup-python@v4. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

also there was an issue made for this on setup-python repo: https://github.com/actions/setup-python/issues/735
to which it concluded to update from v4 to v5 version of the script.

there seem to be a lot changing from v4 to v5 of the action: https://github.com/actions/setup-python/compare/v4.8.0...v5.0.0
though how it may effect CI is a little unknown to me. If openpilot depends on node 16, does this change effect it in any way?
for me it was a single letter change which had no apparent consequences beside faster run: https://github.com/ParsaNobahari/agnos-builder/actions/runs/10058336752

**Comment by adeebshihadeh** [comment]
Want to make a PR to update it?
