### ISSUE TITLE
Build + push full release in CI

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/agnos-builder#272]
The goal is to have CI output a full manifest you can drop in an openpilot branch for easy testing. Here's an example AGNOS update: https://github.com/commaai/openpilot/pull/32373.

The workflow will then be:
* push your changes to a PR
* bump the AGNOS version
* CI gives you a manifest to drop in an openpilot branch
* share on Discord for easy testing, or try it yourself

**Comment by andiradulescu** [comment]
As explained [here](https://github.com/commaai/agnos-builder/pull/275#issuecomment-2266681174), GitHub artifacts are always zip files. As for Releases/Prereleases (and the required tags) they will spam the agnos-builder repo [a lot](https://github.com/actions/upload-artifact/issues/27#issuecomment-581381318).

So, the only ways I can see this working:
- use GH releases and write a zip stream decompressor (in openpilot) specifically for the zip format used in GitHub CI
- use Azure (with secrets added in the repo) to upload usual xz files packaged by `package_ota.py`

Azure seems the cleanest way.
