### ISSUE TITLE
build python with optimizations

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/agnos-builder#30]
Seeing about a 10% improvement in controlsd with a quick test. Also worth trying to build capnproto with LTO and PGO.

For bounty, make sure to post before/after benchmarks.

**Comment by pantew869** [comment]
> Also worth trying to build capnproto with LTO and PGO.
Should capnproto be profiled with openpilot unit-tests?

**Comment by andiradulescu** [comment]
added https://github.com/commaai/agnos-builder/issues/353 for capnproto
