### ISSUE TITLE
Ship ABL without fastboot, 3s boot time savings

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/agnos-builder#320]
Background in https://github.com/commaai/flash/issues/7

Requirements:
- [x] flash.comma.ai flashes over QDL https://github.com/commaai/flash/pull/39
- [x] QDL flashing time is less than or equal to the optimized fastboot flashing time
- [x] remove the `system-skip-chunks` image from the build process, background in https://github.com/commaai/agnos-builder/pull/275

Once all these are done, I'll push the ABL without fastboot.

**Comment by andiradulescu** [comment]
skip-chunks cleanup: https://github.com/commaai/agnos-builder/pull/367
