### ISSUE TITLE
tethering no longer works

### ISSUE THREAD

**Issue by sshane** [commaai/agnos-builder#386]
`selfdrive/ui/qt/network/wifi_manager.cc: DBus call error: "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."`

Also broken for setting connection settings, such as which AP BSSID to connect to

**Comment by adeebshihadeh** [comment]
@deanlee any idea why this is? Does 24.04 have a different NetworkManager API?

**Comment by deanlee** [comment]
The NetworkManager dbus interface usually doesn’t change across versions. Is it possible that DBus policies or permissions in `/etc/dbus-1/system.d` were updated with the upgrade?

**Comment by adeebshihadeh** [comment]
Turns out NetworkManager was crashing due to the netplan config.
