### ISSUE TITLE
Show dongle ID and other info in tmux bar

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/agnos-builder#405]
Maybe also temperature? 

`/sys/devices/virtual/thermal/thermal_zone11` is a good one to use for temperature (it's the GPU).

![image](https://github.com/user-attachments/assets/c7c9151c-8961-4eb5-83d7-5d7fa4b6e96c)

**Comment by Kaweees** [comment]
I'm interested in tackling this issue, if it's already not taken

**Comment by Kaweees** [comment]
I'm interested in tackling this issue, if it's already not taken

**Comment by martinl** [comment]
if there is no PR then it is not taken, push one and make it draft to get started

**Comment by adeebshihadeh** [comment]
https://github.com/commaai/agnos-builder/commit/2c089d3665a520a743d9658c4a94ea26bff6e9ed
