### ISSUE TITLE
segmentation fault when pressing screen on network setup

### ISSUE THREAD

**Issue by BBBmau** [commaai/agnos-builder#416]
when building system image and flashing on device I get the following segmentation fault:
`/usr/comma/comma.sh: line 100: 15015 Segmentation fault      (core dumped) $SETUP`

This comes from moving to the network select page, when I attempt to press a network it shifts to the comma logo with the output above when serialling in the console.

Unsure of which commit this comes from, investigating.

edit: also a ui segment fault that comes up when no setup is needed:
`{'tombstone': 'selfdrive/ui/ui - Signal: 11 (SIGSEGV) - SinalName: SIGSEGV -  in main  at selfdrive/ui/main.cc:23'}`

**Comment by adeebshihadeh** [comment]
https://github.com/commaai/agnos-builder/pull/419
