### ISSUE TITLE
ModemManager: try all APNs

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/agnos-builder#47]
Currently, ModemManager only seems to try the first APN for a provider. It will keep trying to connect and fail with the first APN for the provider.

**Comment by adeebshihadeh** [comment]
dd39e9258194309b528f2c8014e9fdc5a792f49f may be related

**Comment by pd0wm** [comment]
Also try no APN if none of them work.

**Comment by adeebshihadeh** [comment]
This may be fixed with #63.
