### ISSUE TITLE
Don't ship sparsified OTA images

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/agnos-builder#5]
This is just for setting sparse=False for the system image openpilot downloads in agnos.json

**Comment by andiradulescu** [comment]
Will take care of this as soon as I finish with https://github.com/commaai/agnos-builder/pull/246

**Comment by andiradulescu** [comment]
I'm a little confused on which type of image:
- raw
- sparsified
- sparsified with skip chunks

flashes in how much time with:
- fastboot
- edl

I will use the same host, cable and device, run some comparisons and come up with a table.

**Comment by andiradulescu** [comment]
Can you shortly explain the relation to https://github.com/commaai/openpilot/issues/31494? Or the compatibility between the two?

What will `agnos-builder` ship when both issues are `Closed`?
