### ISSUE TITLE
How could I build my own customized "/usr/comma/setup" ?

### ISSUE THREAD

**Issue by joeking11829** [commaai/agnos-builder#94]
Hi comma teams,

How could I build my own customized "/usr/comma/setup" to disable the PubMasters of "gpsLocationExternal" and "sensorEvents"  ?
Because I wanna to launch the "tools/sim/bridge.py" inside C3.

Thanks !!

**Comment by adeebshihadeh** [comment]
The setup source is here: https://github.com/commaai/openpilot/blob/master/selfdrive/ui/qt/setup/setup.cc

**Comment by joeking11829** [comment]
> The setup source is here: https://github.com/commaai/openpilot/blob/master/selfdrive/ui/qt/setup/setup.cc

@adeebshihadeh 
Thanks for your quick reply.
