### ISSUE TITLE
Get "PermissionError: [Errno 1] Operation not permitted" when running "sched_setscheduler" on C3

### ISSUE THREAD

**Issue by joeking11829** [commaai/agnos-builder#95]
Hi comma teams,

I wanna to run "[../launch_openpilot.sh](https://github.com/commaai/openpilot/blob/master/launch_openpilot.sh)" on C3 via ssh terminal.
But when "radard" and "controlsd" run the "config_realtime_process" inside "[../common/realtime.py](https://github.com/commaai/openpilot/blob/master/common/realtime.py#L42)". 
It gets "PermissionError: [Errno 1] Operation not permitted".

How should I fix this error ?

Thanks!!

**Comment by incognitojam** [comment]
This isn't relevant to agnos builder
